In [1]:
import pandas as pd
import numpy as np

In [11]:
# df = pd.read_excel("~/Downloads/20250630湖北省2025年专家版合并2024院校分（25招生计划）.xlsx", header=[0, 1, 2])
df = pd.read_excel("~/Downloads/湖北2025招生计划(含新增).xlsx", header=[0, 1, 2])
# 修改列名，添加前缀（三行标题）
df.columns = ['{}_{}'.format(str(b), str(c)) if str(b) != 'nan' else str(c) for a, b, c in df.columns]
# 对于两行标题（）
# df.columns = ['{}_{}'.format(str(a), str(b)) if str(a) != 'nan' else str(b) for a, b in df.columns]

In [12]:
df.head()

,2025招生计划_省份,2025招生计划_年份,2025招生计划_院校,2025招生计划_院校代码,2025招生计划_专业组,2025招生计划_专业组代码,2025招生计划_专业,2025招生计划_专业代码,2025招生计划_专业类,2025招生计划_专业备注,...,专业信息介绍_是否国家特色,专业信息介绍_软科排名,专业信息介绍_专业荣誉,专业信息介绍_本校硕士,专业信息介绍_本校博士,专业信息介绍_硕士点数量,专业信息介绍_硕士点专业,专业信息介绍_博士点数量,专业信息介绍_博士点专业,专业信息介绍_id
0,湖北,2025,北京大学,A001,08组,8,数学类,31,数学类,(数学与应用数学(数学)、数学与应用数学(概率统计)、数学与应用数学(科学与工程计算)、数学...,...,NaN,1.0,未名学者数学拔尖学生培养基地,教育（专硕）；数学；统计学,教育（专博）；数学；统计学,78.0,保险(专)；博物馆(专)；材料科学与工程；材料与化工(专)；测绘科学与技术；大气科学；地理学...,68.0,材料科学与工程；材料与化工(专)；测绘科学与技术；大气科学；地理学；地球物理学；地质学；电子...,A0010831
1,湖北,2025,北京大学,A001,08组,8,工科试验班类,32,工科试验班类,(理论与应用力学、工程力学、能源与环境系统工程、航空航天工程、生物医学工程、材料科学与工程),...,NaN,NaN,NaN,NaN,NaN,78.0,保险(专)；博物馆(专)；材料科学与工程；材料与化工(专)；测绘科学与技术；大气科学；地理学...,68.0,材料科学与工程；材料与化工(专)；测绘科学与技术；大气科学；地理学；地球物理学；地质学；电子...,A0010832
2,湖北,2025,北京大学,A001,08组,8,物理学类,33,物理学类,(物理学、大气科学(大气与海洋)),...,NaN,1.0,省一/未名学者物理学拔尖学生培养基地,教育（专硕）；物理学,教育（专博）；物理学,78.0,保险(专)；博物馆(专)；材料科学与工程；材料与化工(专)；测绘科学与技术；大气科学；地理学...,68.0,材料科学与工程；材料与化工(专)；测绘科学与技术；大气科学；地理学；地球物理学；地质学；电子...,A0010833
3,湖北,2025,北京大学,A001,08组,8,天文学,34,天文学类,(天体物理、天文高新技术和应用),...,NaN,3.0,国一/未名学者天文学拔尖学生培养基地,NaN,天文学,78.0,保险(专)；博物馆(专)；材料科学与工程；材料与化工(专)；测绘科学与技术；大气科学；地理学...,68.0,材料科学与工程；材料与化工(专)；测绘科学与技术；大气科学；地理学；地球物理学；地质学；电子...,A0010834
4,湖北,2025,北京大学,A001,08组,8,电子信息类,35,电子信息类,(电子信息科学与技术、微电子科学与工程),...,NaN,1.0,国一,信息与通信工程；电子信息（专硕）；电子科学与技术,信息与通信工程；电子信息（专博）；电子科学与技术,78.0,保险(专)；博物馆(专)；材料科学与工程；材料与化工(专)；测绘科学与技术；大气科学；地理学...,68.0,材料科学与工程；材料与化工(专)；测绘科学与技术；大气科学；地理学；地球物理学；地质学；电子...,A0010835

In [58]:
df.describe(include='all')

,2025招生计划_省份,2025招生计划_年份,2025招生计划_院校,2025招生计划_院校代码,2025招生计划_专业组,2025招生计划_专业组代码,2025招生计划_专业,2025招生计划_专业代码,2025招生计划_专业类,2025招生计划_专业备注,...,专业信息介绍_是否国家特色,专业信息介绍_软科排名,专业信息介绍_专业荣誉,专业信息介绍_本校硕士,专业信息介绍_本校博士,专业信息介绍_硕士点数量,专业信息介绍_硕士点专业,专业信息介绍_博士点数量,专业信息介绍_博士点专业,专业信息介绍_id
count,29439,29439.0,29439,29439,29439,29439.000000,29439,29439,29439,17397,...,1703,11766.000000,9791,12010,5333,14717.000000,14700,11537.000000,11520,29439
unique,1,NaN,1709,1709,33,NaN,1186,171,184,7018,...,1,NaN,140,366,253,NaN,624,NaN,378,29439
top,湖北,NaN,武汉工程大学,C109,01组,NaN,英语,01,计算机类,(师范类),...,是,NaN,国一,机械工程； 机械（专硕）,应用经济学,NaN,安全科学与工程；材料科学与工程；材料与化工(专)；城乡规划(专)；电气工程(专)；电子信息(...,NaN,中西医结合；中药学；中医(专)；中医学,A0010831
freq,29439,NaN,171,171,6989,NaN,484,1630,2730,445,...,1703,NaN,5207,469,215,NaN,171,NaN,183,1
mean,NaN,2025.0,NaN,NaN,NaN,4.137539,NaN,NaN,NaN,NaN,...,NaN,84.280299,NaN,NaN,NaN,41.048108,NaN,15.699575,NaN,NaN
std,NaN,0.0,NaN,NaN,NaN,3.887822,NaN,NaN,NaN,NaN,...,NaN,83.888307,NaN,NaN,NaN,23.320838,NaN,16.004736,NaN,NaN
min,NaN,2025.0,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,...,NaN,1.000000,NaN,NaN,NaN,1.000000,NaN,1.000000,NaN,NaN
25%,NaN,2025.0,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,NaN,...,NaN,19.000000,NaN,NaN,NaN,25.000000,NaN,5.000000,NaN,NaN
50%,NaN,2025.0,NaN,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,...,NaN,58.000000,NaN,NaN,NaN,41.000000,NaN,10.000000,NaN,NaN
75%,NaN,2025.0,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,...,NaN,123.000000,NaN,NaN,NaN,55.000000,NaN,21.000000,NaN,NaN
max,NaN,2025.0,NaN,NaN,NaN,33.000000,NaN,NaN,NaN,NaN,...,NaN,492.000000,NaN,NaN,NaN,111.000000,NaN,78.000000,NaN,NaN

In [14]:
df.columns

Index(['2025招生计划_省份', '2025招生计划_年份', '2025招生计划_院校', '2025招生计划_院校代码',
       '2025招生计划_专业组', '2025招生计划_专业组代码', '2025招生计划_专业', '2025招生计划_专业代码',
       '2025招生计划_专业类', '2025招生计划_专业备注', '2025招生计划_科目', '2025招生计划_选科要求',
       '2025招生计划_类型', '2025招生计划_批次', '2025招生计划_是否新增', '2025招生计划_计划人数',
       '2025招生计划_学制', '2025招生计划_学费', '2025招生计划_组内专业', '24专业组数据_最低分',
       '24专业组数据_最低分位次', '24专业组数据_录取人数', '24年专业录取数据_年份1', '24年专业录取数据_最高分1',
       '24年专业录取数据_最高分位次1', '24年专业录取数据_平均分1', '24年专业录取数据_平均分位次1',
       '24年专业录取数据_最低分1', '24年专业录取数据_最低分位次1', '24年专业录取数据_录取人数1',
       '23年专业录取数据_年份2', '23年专业录取数据_最高分2', '23年专业录取数据_最高分位次2', '23年专业录取数据_平均分2',
       '23年专业录取数据_平均分位次2', '23年专业录取数据_最低分2', '23年专业录取数据_最低分位次2',
       '23年专业录取数据_录取人数2', '22年专业录取数据_年份3', '22年专业录取数据_最高分3',
       '22年专业录取数据_最高分位次3', '22年专业录取数据_平均分3', '22年专业录取数据_平均分位次3',
       '22年专业录取数据_最低分3', '22年专业录取数据_最低分位次3', '22年专业录取数据_录取人数3', '院校信息介绍_院校省份',
       '院校信息介绍_院校城市', '院校信息介绍_城市等级', '院校信息介绍_院校类型', '院校信息介绍_办学性质',
       '院校信息介绍_隶属部门', '院校信息介绍_院校标签', '院校信息介绍_院校层级', '院校信息介绍_院校排名',
       '院校信息介绍_院校简介', '院校信息介绍_招生简章', '院校信息介绍_院系设置', '院校信息介绍_更名合并情况',
       '院校信息介绍_转专业情况', '院校信息介绍_保研率', '专业信息介绍_是否双一流', '专业信息介绍_学科评估等级',
       '专业信息介绍_是否国家特色', '专业信息介绍_软科排名', '专业信息介绍_专业荣誉', '专业信息介绍_本校硕士',
       '专业信息介绍_本校博士', '专业信息介绍_硕士点数量', '专业信息介绍_硕士点专业', '专业信息介绍_博士点数量',
       '专业信息介绍_博士点专业', '专业信息介绍_id'],
      dtype='object')

In [19]:
"""数据库字段
id: UInt32                            # 记录唯一标识
school_code: String                  # 院校代码
school_name: String                  # 院校名称
major_code: String                   # 专业代码
major_name: String                   # 专业名称
major_group_code: String            # 专业组代码
source_province: LowCardinality(String) # 生源地，固定为湖北
school_province: LowCardinality(String) # 院校所在省份
school_city: String                 # 院校所在城市
admission_batch: LowCardinality(String) # 录取批次
subject_category: Enum8('物理'=1, '历史'=2) # 科类：物理类或历史类
require_physics: Bool               # 是否要求选择物理
require_chemistry: Bool             # 是否要求选择化学
require_biology: Bool               # 是否要求选择生物
require_politics: Bool              # 是否要求选择政治
require_history: Bool               # 是否要求选择历史
require_geography: Bool             # 是否要求选择地理
subject_requirement_raw: LowCardinality(String) # 原始选科限制描述，用于显示
school_type: LowCardinality(String) # 院校类型
school_ownership: Enum8('公办'=1, '民办'=2) # 公办或民办
school_authority: LowCardinality(String) # 院校隶属单位
school_level: LowCardinality(String) # 院校水平层次
school_tags: String                 # 院校标签，如985、211等
education_level: Enum8('本科'=1, '专科'=2) # 本科或专科
major_description: String           # 专业备注信息
tuition_fee: UInt32                # 学费（元/年）
is_new_major: Bool                  # 是否为新增专业
min_score_2024: UInt16              # 2024年专业组最低录取分数
min_rank_2024: UInt32               # 2024年专业组最低录取位次
enrollment_plan_2024: UInt16        # 2024年招生计划数
is_science: Bool                    # 是否为理科专业
is_engineering: Bool                # 是否为工科专业
is_medical: Bool                    # 是否为医科专业
is_economics_mgmt_law: Bool         # 是否为经管法专业
is_liberal_arts: Bool               # 是否为文科专业（非经管法）
is_design_arts: Bool                # 是否为设计与艺术类专业
is_language: Bool                   # 是否为语言类专业
study_years: Nullable(String)       # 学制（可能为空）
major_min_score_2024: Nullable(UInt16) # 专业最低分（可能为空）
"""
print("当前数据库表结构")

当前数据库表结构

## 数据清洗和映射

现在开始将Excel数据映射到ClickHouse表结构中

In [25]:
# 创建新的DataFrame用于存储清洗后的数据
cleaned_df = pd.DataFrame()

### 1. 处理计划相关

In [62]:
import pandas as pd

def find_key_columns(df, keywords):
    """
    查找包含特定关键词的列名
    :param df: DataFrame
    :param keywords: 关键词列表
    :return: 包含关键词的列名列表
    """
    key_columns = []
    for col in df.columns:
        if any(keyword in col for keyword in keywords):
            key_columns.append(col)

    print("院校相关列:")
    for i, col in enumerate(key_columns):
        print(f"{i+1}: {col}")

    # 取每个关键列的前2个值，构建纵向表格
    preview_data = []
    for col in key_columns:
        values = df[col].head(2).tolist()
        preview_data.append([col] + values)

    # 构建DataFrame，第一列为列名，后面为前2个值
    preview_vertical_df = pd.DataFrame(preview_data, columns=['列名', '样例1', '样例2'])
    display(preview_vertical_df)

college_key_words = ['招生计划']
find_key_columns(df, college_key_words)

院校相关列:
1: 2025招生计划_省份
2: 2025招生计划_年份
3: 2025招生计划_院校
4: 2025招生计划_院校代码
5: 2025招生计划_专业组
6: 2025招生计划_专业组代码
7: 2025招生计划_专业
8: 2025招生计划_专业代码
9: 2025招生计划_专业类
10: 2025招生计划_专业备注
11: 2025招生计划_科目
12: 2025招生计划_选科要求
13: 2025招生计划_类型
14: 2025招生计划_批次
15: 2025招生计划_是否新增
16: 2025招生计划_计划人数
17: 2025招生计划_学制
18: 2025招生计划_学费
19: 2025招生计划_组内专业

,列名,样例1,样例2
0,2025招生计划_省份,湖北,湖北
1,2025招生计划_年份,2025,2025
2,2025招生计划_院校,北京大学,北京大学
3,2025招生计划_院校代码,A001,A001
4,2025招生计划_专业组,08组,08组
5,2025招生计划_专业组代码,8,8
6,2025招生计划_专业,数学类,工科试验班类
7,2025招生计划_专业代码,31,32
8,2025招生计划_专业类,数学类,工科试验班类
9,2025招生计划_专业备注,(数学与应用数学(数学)、数学与应用数学(概率统计)、数学与应用数学(科学与工程计算)、数学...,(理论与应用力学、工程力学、能源与环境系统工程、航空航天工程、生物医学工程、材料科学与工程)
10,2025招生计划_科目,物理,物理
11,2025招生计划_选科要求,化学,化学
12,2025招生计划_类型,NaN,NaN
13,2025招生计划_批次,本科批,本科批
14,2025招生计划_是否新增,NaN,NaN
15,2025招生计划_计划人数,1,4
16,2025招生计划_学制,4,4
17,2025招生计划_学费,5000,5000
18,2025招生计划_组内专业,31 数学类 (数学与应用数学(数学)、数学与应用数学(概率统计)、数学与应用数学(科学与工...,31 数学类 (数学与应用数学(数学)、数学与应用数学(概率统计)、数学与应用数学(科学与工...

In [66]:
# 院校字段映射
cleaned_df['major_id'] = (
    df['2025招生计划_院校代码'].astype(str) +
    df['2025招生计划_专业组代码'].apply(lambda x: f"{int(x):02d}" if pd.notnull(x) else print("专业组代码：无法转换为整数")) +
    df['2025招生计划_专业代码'].astype(str)
)
cleaned_df['school_name'] = df['2025招生计划_院校'].fillna('')
cleaned_df['school_code'] = df['2025招生计划_院校代码'].fillna('')
cleaned_df['major_group_code'] = df['2025招生计划_专业组代码'].apply(lambda x: f"{int(x):02d}" if pd.notnull(x) else print("专业组代码：无法转换为整数"))
cleaned_df['major_name'] = df['2025招生计划_专业'].fillna('')
cleaned_df['major_code'] = df['2025招生计划_专业代码'].fillna('')
cleaned_df['major_category'] = df['2025招生计划_专业类'].fillna('')
cleaned_df['major_description'] = df['2025招生计划_专业备注'].fillna('')
# 生源地字段映射
cleaned_df['source_province'] = df['2025招生计划_省份']
# 科类映射
cleaned_df['subject_category'] = df['2025招生计划_科目'].map({'物理': '物理', '历史': '历史'})
# 选科要求原始数据，用于显示
cleaned_df['subject_requirement_raw'] = df['2025招生计划_选科要求']
# 学费
cleaned_df['tuition_fee'] = df['2025招生计划_学费'].fillna('')
cleaned_df['is_new_major'] = df['2025招生计划_是否新增'].map(lambda x: True if x == '新增' else False).fillna(False)
cleaned_df['admission_batch'] = df['2025招生计划_批次'].fillna('')
# 招生计划
cleaned_df['enrollment_plan'] = df['2025招生计划_计划人数'].fillna(0).astype(int)
cleaned_df['enrollment_type'] = df['2025招生计划_类型'].fillna('')
cleaned_df['enrollment_plan_year'] = df['2025招生计划_年份'].fillna(2025).astype(int)
# 招生计划-兼容考虑
cleaned_df['enrollment_plan_2024'] = df['2025招生计划_计划人数'].fillna(0).astype(int)
# 学制
cleaned_df['study_duration'] = df['2025招生计划_学制'].fillna('')

print("【专业】字段映射【初步】完成，即将开始选科处理")
print(f"数据行数: {len(cleaned_df)}")
# 查看数据分布
# 显示数据描述和空值统计
display(cleaned_df.describe(include='all'))

【专业】字段映射【初步】完成，即将开始选科处理
数据行数: 29439

,school_code,school_name,major_code,major_name,major_group_code,source_province,subject_category,subject_requirement_raw,tuition_fee,is_new_major,...,enrollment_type,enrollment_plan_year,require_physics,require_chemistry,require_biology,require_politics,require_history,require_geography,major_category,major_description
count,29439,29439,29439,29439,29439,29439,29439,29439,29439,29439,...,29439,29439.0,29439,29439,29439,29439,29439,29439,29439,29439
unique,1709,1709,171,1186,33,1,2,11,522,2,...,6,NaN,2,2,2,2,2,2,184,7019
top,C109,武汉工程大学,01,英语,01,湖北,物理,不限,5000,False,...,,NaN,True,False,False,False,False,False,计算机类,
freq,171,171,1630,484,6989,29439,20160,18215,4828,23021,...,27520,NaN,20190,18690,29089,29207,20160,29291,2730,12042
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2025.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2025.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2025.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2025.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2025.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2025.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [68]:
# 选科要求字段解析
def check_subject(subject, row):
    # 检查选科要求原始字段是否包含该学科
    if subject in str(row['subject_requirement_raw']):
        return True
    # 检查科类字段是否包含该学科
    if subject in str(row['subject_category']):
        return True
    return False

cleaned_df['require_physics'] = cleaned_df.apply(lambda row: check_subject('物', row), axis=1)
cleaned_df['require_chemistry'] = cleaned_df.apply(lambda row: check_subject('化', row), axis=1)
cleaned_df['require_biology'] = cleaned_df.apply(lambda row: check_subject('生', row), axis=1)
cleaned_df['require_politics'] = cleaned_df.apply(lambda row: check_subject('政', row), axis=1)
cleaned_df['require_history'] = cleaned_df.apply(lambda row: check_subject('历', row), axis=1)
cleaned_df['require_geography'] = cleaned_df.apply(lambda row: check_subject('地', row), axis=1)

print("选科要求字段解析完成")
print("选科要求统计:")
print(f"要求物理: {cleaned_df['require_physics'].sum()}")
print(f"要求化学: {cleaned_df['require_chemistry'].sum()}")
print(f"要求生物: {cleaned_df['require_biology'].sum()}")
print(f"要求政治: {cleaned_df['require_politics'].sum()}")
print(f"要求历史: {cleaned_df['require_history'].sum()}")
print(f"要求地理: {cleaned_df['require_geography'].sum()}")
print("【专业】字段解析全部完成")
cleaned_df.head()

选科要求字段解析完成
选科要求统计:
要求物理: 20190
要求化学: 10749
要求生物: 350
要求政治: 232
要求历史: 9279
要求地理: 148
【专业】字段解析全部完成

,school_code,school_name,major_code,major_name,major_group_code,source_province,subject_category,subject_requirement_raw,tuition_fee,is_new_major,...,enrollment_type,enrollment_plan_year,require_physics,require_chemistry,require_biology,require_politics,require_history,require_geography,major_category,major_description
0,A001,北京大学,31,数学类,08,湖北,物理,化学,5000,False,...,,2025,True,True,False,False,False,False,数学类,(数学与应用数学(数学)、数学与应用数学(概率统计)、数学与应用数学(科学与工程计算)、数学...
1,A001,北京大学,32,工科试验班类,08,湖北,物理,化学,5000,False,...,,2025,True,True,False,False,False,False,工科试验班类,(理论与应用力学、工程力学、能源与环境系统工程、航空航天工程、生物医学工程、材料科学与工程)
2,A001,北京大学,33,物理学类,08,湖北,物理,化学,5000,False,...,,2025,True,True,False,False,False,False,物理学类,(物理学、大气科学(大气与海洋))
3,A001,北京大学,34,天文学,08,湖北,物理,化学,5000,False,...,,2025,True,True,False,False,False,False,天文学类,(天体物理、天文高新技术和应用)
4,A001,北京大学,35,电子信息类,08,湖北,物理,化学,5300,False,...,,2025,True,True,False,False,False,False,电子信息类,(电子信息科学与技术、微电子科学与工程)

### 2. 历年数据解析

2.1 历年分数线解析

In [73]:
import json

def load_score_rank(year, category):
    """
    根据规则读取数据
    """
    # category: 'physics' or 'history'
    category_map = {'physics': '物理', 'history': '历史'}
    filename = f'../static/score_rank_hubei_{year}_{category}.json'
    with open(filename, 'r', encoding='utf-8') as f:
        score_rank = json.load(f)
    subject = category_map[category]
    score_rank_map = {int(item['score']): int(item['accumulate']) for item in score_rank["data"]}
    max_score = max(score_rank_map.keys())
    score_rank_map = {k: v for k, v in score_rank_map.items()}
    # 额外记录最高分
    score_rank_map['max_score'] = str(max_score)
    return f"{year}_{subject}", score_rank_map

# 科目-分数-位次映射
subject_score_rank_map = {}
for cat in ['physics', 'history']:
    key, score_rank_map = load_score_rank(2024, cat)
    subject_score_rank_map[key] = score_rank_map

# 简要查看subject_score_rank_map内容
for subject_key, score_rank in subject_score_rank_map.items():
    print(f"{subject_key}: 共{len(score_rank)-1}个分数-位次映射，分数范围: {min(int(k) for k in score_rank if k != 'max_score')}~{score_rank['max_score']}")
    preview = list(score_rank.items())[:5]
    print("  示例:", preview, " 最高分",score_rank['max_score'])

2024_物理: 共546个分数-位次映射，分数范围: 150~695
  示例: [(695, 44), (694, 50), (693, 60), (692, 71), (691, 83)]  最高分 695
2024_历史: 共521个分数-位次映射，分数范围: 150~670
  示例: [(670, 9), (669, 10), (668, 12), (667, 12), (666, 15)]  最高分 670

In [74]:
# 查看数据表关于特定年份信息
year = "24"

college_key_words = [year]
find_key_columns(df, college_key_words)

院校相关列:
1: 24专业组数据_最低分
2: 24专业组数据_最低分位次
3: 24专业组数据_录取人数
4: 24年专业录取数据_年份1
5: 24年专业录取数据_最高分1
6: 24年专业录取数据_最高分位次1
7: 24年专业录取数据_平均分1
8: 24年专业录取数据_平均分位次1
9: 24年专业录取数据_最低分1
10: 24年专业录取数据_最低分位次1
11: 24年专业录取数据_录取人数1

                  列名     样例1     样例2
0        24专业组数据_最低分   691.0   691.0
1      24专业组数据_最低分位次    83.0    83.0
2       24专业组数据_录取人数     NaN     NaN
3      24年专业录取数据_年份1  2024.0  2024.0
4     24年专业录取数据_最高分1     NaN     NaN
5   24年专业录取数据_最高分位次1     NaN     NaN
6     24年专业录取数据_平均分1     NaN     NaN
7   24年专业录取数据_平均分位次1     NaN     NaN
8     24年专业录取数据_最低分1   691.0   691.0
9   24年专业录取数据_最低分位次1    83.0    83.0
10   24年专业录取数据_录取人数1     NaN     NaN

In [76]:
# 2024年录取数据
# 【专业组】数据
cleaned_df['min_score_2024'] = pd.to_numeric(df['24专业组数据_最低分'], errors='coerce').fillna(0).astype(int)
cleaned_df['min_rank_2024'] = pd.to_numeric(df['24专业组数据_最低分位次'], errors='coerce').fillna(0).astype(int)
cleaned_df['admission_num_2024'] = pd.to_numeric(df['24专业组数据_录取人数'], errors='coerce').fillna(0).astype(int)
# 【专业】数据
cleaned_df['major_min_score_2024'] = pd.to_numeric(df['24年专业录取数据_最低分1'], errors='coerce').fillna(0).astype(int)
cleaned_df['major_min_rank_2024'] = pd.to_numeric(df['24年专业录取数据_最低分位次1'], errors='coerce').fillna(0).astype(int)
cleaned_df['major_avg_score_2024'] = pd.to_numeric(df['24年专业录取数据_平均分1'], errors='coerce').fillna(0).astype(int)
cleaned_df['major_avg_rank_2024'] = pd.to_numeric(df['24年专业录取数据_平均分位次1'], errors='coerce').fillna(0).astype(int)
cleaned_df['major_max_score_2024'] = pd.to_numeric(df['24年专业录取数据_最高分1'], errors='coerce').fillna(0).astype(int)
cleaned_df['major_max_rank_2024'] = pd.to_numeric(df['24年专业录取数据_最高分位次1'], errors='coerce').fillna(0).astype(int)
cleaned_df['major_admission_num_2024'] = pd.to_numeric(df['24年专业录取数据_录取人数1'], errors='coerce').fillna(0).astype(int)

selected_columns = [
    'min_score_2024',
    'min_rank_2024',
    'admission_num_2024',
    'major_min_score_2024',
    'major_min_rank_2024',
    'major_avg_score_2024',
    'major_avg_rank_2024',
    'major_max_score_2024',
    'major_max_rank_2024',
    'major_admission_num_2024',
]
# 显示2024年数据分析
display(cleaned_df[selected_columns].describe())

,min_score_2024,min_rank_2024,admission_num_2024,major_min_score_2024,major_min_rank_2024,major_avg_score_2024,major_avg_rank_2024,major_max_score_2024,major_max_rank_2024,major_admission_num_2024
count,29439.000000,29439.000000,29439.000000,29439.000000,29439.000000,29439.000000,29439.000000,29439.000000,29439.000000,29439.000000
mean,430.784470,76728.672679,45.939536,373.608037,61037.426271,161.925439,14202.435647,199.207718,16599.757023,3.800299
std,166.638724,67077.783518,156.976730,219.325833,64885.015291,249.781855,31431.757214,264.169309,32593.573783,14.867534
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,352.000000,19537.000000,0.000000,257.000000,4361.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,483.000000,62370.000000,0.000000,453.000000,40713.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,551.000000,116472.000000,16.000000,545.000000,97720.000000,491.000000,10670.000000,522.000000,18550.000000,2.000000
max,691.000000,245038.000000,1630.000000,691.000000,245038.000000,667.000000,241696.000000,671.000000,241100.000000,374.000000

### 院校信息处理

In [80]:
# 统一tag字段的分隔方式
def unify_tag_columns(tag):
    # 将标签字段的分隔符统一为英文逗号
    if isinstance(tag, str):
        tag = tag.strip()
        tag = tag.replace('，', ',')
        tag = tag.replace('/', ',')
        tag = tag.replace(' ', ',')
        # 去除重复逗号和首尾逗号
        tag = ','.join([t for t in tag.split(',') if t.strip()])
    return tag

In [81]:
college_key_words = ['院校信息']
find_key_columns(df, college_key_words)

院校相关列:
1: 院校信息介绍_院校省份
2: 院校信息介绍_院校城市
3: 院校信息介绍_城市等级
4: 院校信息介绍_院校类型
5: 院校信息介绍_办学性质
6: 院校信息介绍_隶属部门
7: 院校信息介绍_院校标签
8: 院校信息介绍_院校层级
9: 院校信息介绍_院校排名
10: 院校信息介绍_院校简介
11: 院校信息介绍_招生简章
12: 院校信息介绍_院系设置
13: 院校信息介绍_更名合并情况
14: 院校信息介绍_转专业情况
15: 院校信息介绍_保研率

,列名,样例1,样例2
0,院校信息介绍_院校省份,北京,北京
1,院校信息介绍_院校城市,海淀区,海淀区
2,院校信息介绍_城市等级,一线城市,一线城市
3,院校信息介绍_院校类型,综合,综合
4,院校信息介绍_办学性质,公办,公办
5,院校信息介绍_隶属部门,教育部,教育部
6,院校信息介绍_院校标签,985/211/双一流/国重点/保研资格/原卫生部直属/基础学科拔尖/卓越医生/卓越法律/五...,985/211/双一流/国重点/保研资格/原卫生部直属/基础学科拔尖/卓越医生/卓越法律/五...
7,院校信息介绍_院校层级,本科,本科
8,院校信息介绍_院校排名,2.0,2.0
9,院校信息介绍_院校简介,NaN,NaN
10,院校信息介绍_招生简章,https://gaokao.chsi.com.cn/zsgs/zhangcheng/lis...,https://gaokao.chsi.com.cn/zsgs/zhangcheng/lis...
11,院校信息介绍_院系设置,NaN,NaN
12,院校信息介绍_更名合并情况,2000年，北京医科大学并入,2000年，北京医科大学并入
13,院校信息介绍_转专业情况,NaN,NaN
14,院校信息介绍_保研率,58.6%,58.6%

In [84]:
# 提取所有院校层级的唯一标签（以/分隔）
all_tags = df["院校信息介绍_院校标签"].dropna().astype(str).str.split("/")
unique_tags = set(tag.strip() for tags in all_tags for tag in tags if tag.strip())
print(sorted(unique_tags))

['211', '985', 'C9联盟', 'E9联盟', '两外一法', '两电一邮', '中坚九校', '乡村振兴人才培养优质校', '乡村振兴优质校', '五财一贸', '五院四系', '保研资格', '八大美院', '兵工七子', '军工六校', '华东五校', '卓越中医', '卓越农林', '卓越医生', '卓越医生3+2专科', '卓越工程师', '卓越教师', '卓越法律', '原中医药管理局', '原中国人民银行直属', '原中国船舶总公司直属', '原交通部直属', '原供销合作总社直属', '原兵器部直属', '原农业部直属', '原冶金部直属', '原劳动部直属', '原包装总公司直属', '原化工部直属', '原卫生部直属', '原司法部直属', '原商业部直属', '原国家体委直属', '原国家安监局直属', '原国家旅游局直属', '原国家气象局直属', '原国家测绘局直属', '原国家统计局直属', '原国家质量技监局直属', '原地质部直属', '原外经贸部直属', '原审计署直属', '原建材总局直属', '原建设部直属', '原文化部直属', '原有色金属总公司', '原有色金属总公司直属', '原机械部直属', '原林业部直属', '原核工业部直属', '原民政部直属', '原民航总局直属', '原水利部直属', '原煤炭部直属', '原电力部直属', '原电子工业部直属', '原石油部直属', '原税务总局直属', '原纺织部直属', '原航空航天部直属', '原药监局直属', '原财政部直属', '原轻工业部直属', '原邮电部直属', '原铁道部直属', '双一流', '双高计划', '四大工学院', '国重点', '国防七子', '基础学科拔尖', '建筑新八校', '建筑老八校', '机械四小龙', '现代学徒', '电气二龙', '电气四虎', '省部共建', '省重点', '示范高职', '部委直属', '骨干高职']

In [93]:
school_level_tags = [
    '211', '985', '双一流',
    # '国重点', '省重点','省部共建', '部委直属',
    # '双高计划', '示范高职', '骨干高职', '保研资格',
    # 'C9联盟', 'E9联盟',
    # '中坚九校', '五财一贸', '五院四系',
    # '兵工七子', '军工六校', '国防七子',
    # '卓越中医', '卓越农林', '卓越医生', '卓越医生3+2专科',
    # '卓越工程师', '卓越教师', '卓越法律', '基础学科拔尖',
    # '建筑新八校', '建筑老八校', '四大工学院', '机械四小龙',
    # '电气二龙', '电气四虎',
    # '原中医药管理局', '原中国人民银行直属', '原中国船舶总公司直属',
    # '原交通部直属', '原供销合作总社直属', '原兵器部直属', '原农业部直属',
    # '原冶金部直属', '原劳动部直属', '原包装总公司直属', '原化工部直属',
    # '原卫生部直属', '原司法部直属', '原商业部直属', '原国家体委直属',
    # '原国家安监局直属', '原国家旅游局直属', '原国家气象局直属',
    # '原国家测绘局直属', '原国家统计局直属', '原国家质量技监局直属',
    # '原地质部直属', '原外经贸部直属', '原审计署直属', '原建材总局直属',
    # '原建设部直属', '原文化部直属', '原有色金属总公司', '原有色金属总公司直属',
    # '原机械部直属', '原林业部直属', '原核工业部直属', '原民政部直属',
    # '原民航总局直属', '原水利部直属', '原煤炭部直属', '原电力部直属',
    # '原电子工业部直属', '原石油部直属', '原税务总局直属', '原纺织部直属',
    # '原航空航天部直属', '原药监局直属', '原财政部直属', '原轻工业部直属',
    # '原邮电部直属', '原铁道部直属',
    # '乡村振兴人才培养优质校', '乡村振兴优质校', '现代学徒'
]

In [100]:
# 填充school_province，school_city，school_type，school_ownership，school_authority，school_level，school_tags，education_level
cleaned_df['school_province'] = df['院校信息介绍_院校省份'].fillna('')
cleaned_df['school_city'] = df['院校信息介绍_院校城市'].fillna('')
cleaned_df['school_type'] = df['院校信息介绍_院校类型'].fillna('').apply(unify_tag_columns)
cleaned_df['school_ownership'] = df['院校信息介绍_办学性质'].fillna('')
cleaned_df['school_authority'] = df['院校信息介绍_隶属部门'].fillna('')
# 学校层级 从tags中选择重要字段
cleaned_df['school_level'] = df['院校信息介绍_院校标签'].fillna('').apply(unify_tag_columns).apply(lambda x: ','.join((set(x.split(',')) & set(school_level_tags))))  # 只保留学校层级相关标签
cleaned_df['school_tags'] = df['院校信息介绍_院校标签'].fillna('').apply(unify_tag_columns)
# 本科 / 专科 / 职业本科
cleaned_df['education_level'] = df['院校信息介绍_院校层级'].fillna('')

selected_columns = [
    'school_province', 'school_city', 'school_type', 'school_ownership',
    'education_level', 'school_authority', 'school_level', 'school_tags'
]
# 显示院校信息字段描述
display(cleaned_df[selected_columns].describe(include='all'))

,school_province,school_city,school_type,school_ownership,education_level,school_authority,school_level,school_tags
count,29439,29439,29439,29439,29439,29439,29439,29439
unique,31,345,36,5,3,30,4,380
top,湖北,武汉,理工,公办,本科,省政府,,
freq,8785,5378,10876,22404,20080,16987,24584,13470

In [101]:
# 检查tags字段是否正确设置
# 显示几个school_tags, school_level, 使用unique
print("院校类型 (school_type) 唯一值:")
print(cleaned_df['school_type'].unique())

print("院校层级 (school_level) 唯一值(前五个):")
print(cleaned_df['school_level'].unique()[:5])

print("院校标签 (school_tags) 唯一值(前五个):")
print(cleaned_df['school_tags'].unique()[:5])

院校类型 (school_type) 唯一值:
['综合' '医药' '理工' '综合,理工' '师范' '政法' '财经' '综合,农林' '艺术,语言' '民族' '财经,政法' '语言'
 '综合,师范' '农林' '医药,军事' '体育' '财经,语言' '艺术' '军事' '应用型（中医药）' '综合,其他' '其他'
 '综合,财经' '' '农业' '应用型大学' '综合类' '医学' '工科' '航空' '自然资源' '新工科' '环境' '工业'
 '电影技术' '交通']
院校层级 (school_level) 唯一值(前五个):
['985,211,双一流' '双一流' '211,双一流' '']
院校标签 (school_tags) 唯一值(前五个):
['985,211,双一流,国重点,保研资格,原卫生部直属,基础学科拔尖,卓越医生,卓越法律,五院四系,C9联盟,部委直属'
 '985,211,双一流,国重点,保研资格,原轻工业部直属,基础学科拔尖,卓越工程师,卓越医生,卓越法律,建筑老八校,电气四虎,C9联盟,部委直属'
 '985,211,双一流,国重点,保研资格,基础学科拔尖,卓越工程师,卓越医生,卓越法律,卓越农林,C9联盟,华东五校,建筑新八校,部委直属'
 '985,211,双一流,国重点,保研资格,原卫生部直属,基础学科拔尖,卓越医生,卓越法律,C9联盟,华东五校,部委直属'
 '985,211,双一流,国重点,保研资格,基础学科拔尖,卓越法律,卓越农林,五院四系,部委直属']

### 废弃字段，兼容处理

In [133]:
# 本应该废弃，使用简单数据进行处理
cleaned_df['is_science'] = cleaned_df['subject_category'].apply(lambda x: True if x == '物理' else False)
cleaned_df['is_engineering'] = cleaned_df['major_category'].apply(lambda x: True if '工' in str(x) else False)
cleaned_df['is_medical'] = cleaned_df['major_category'].apply(lambda x: True if '医' in str(x) else False)
cleaned_df['is_economics_mgmt_law'] = cleaned_df['major_category'].apply(lambda x: True if '经管' in str(x) or '法学' in str(x) else False)
cleaned_df['is_liberal_arts'] = cleaned_df['major_category'].apply(lambda x: True if '文' in str(x) and not ('经管' in str(x) or '法学' in str(x)) else False)
cleaned_df['is_design_arts'] = cleaned_df['major_category'].apply(lambda x: True if '设计' in str(x) or '艺术' in str(x) else False)
cleaned_df['is_language'] = cleaned_df['major_category'].apply(lambda x: True if '语言' in str(x) else False)

In [134]:
# 统计处理情况
print("专业分类统计:")
print(f"理科专业: {cleaned_df['is_science'].sum()}")
print(f"工科专业: {cleaned_df['is_engineering'].sum()}")
print(f"医科专业: {cleaned_df['is_medical'].sum()}")
print(f"经管法专业: {cleaned_df['is_economics_mgmt_law'].sum()}")
print(f"文科专业: {cleaned_df['is_liberal_arts'].sum()}")
print(f"设计艺术专业: {cleaned_df['is_design_arts'].sum()}")
print(f"语言类专业: {cleaned_df['is_language'].sum()}")

专业分类统计:
理科专业: 20160
工科专业: 4393
医科专业: 1535
经管法专业: 513
文科专业: 1596
设计艺术专业: 711
语言类专业: 1666

### 主键 ID 的 处理

In [135]:
# 简单的自增
cleaned_df['id'] = range(1, len(cleaned_df) + 1)

### 数据库创建与更新

In [ ]:
import clickhouse_connect

client = clickhouse_connect.create_client(
    host='localhost',
    port=18123,
    username='default',
    password='',
    database='default'
    )

执行列数据分析

In [138]:
def analyze_and_generate_clickhouse_schema(df, enum_threshold=16, string_length_threshold=255):
    """
    自动分析DataFrame并生成ClickHouse建表语句
    
    Parameters:
    df: pandas.DataFrame - 要分析的数据框
    enum_threshold: int - 唯一值数量阈值，低于此值的字符串列会使用Enum类型
    string_length_threshold: int - 字符串长度阈值，超过此长度使用Text类型
    """
    
    schema_info = []
    
    for col_name in df.columns:
        col_data = df[col_name]
        dtype = col_data.dtype
        
        # 统计基本信息
        null_count = col_data.isnull().sum()
        total_count = len(col_data)
        null_ratio = null_count / total_count
        unique_count = col_data.nunique()
        
        # 判断是否需要Nullable
        nullable = null_ratio > 0
        
        print(f"\n分析列: {col_name}")
        print(f"  数据类型: {dtype}")
        print(f"  空值数量: {null_count} ({null_ratio:.2%})")
        print(f"  唯一值数量: {unique_count}")
        
        # 根据数据类型判断ClickHouse类型
        if pd.api.types.is_string_dtype(dtype) or dtype == 'object':
            # 字符串类型处理
            non_null_data = col_data.dropna()
            
            if len(non_null_data) == 0:
                ch_type = 'String'
            elif unique_count <= enum_threshold:
                # 使用Enum类型
                unique_values = non_null_data.unique()
                # 过滤掉过长的值，避免Enum类型过于复杂
                valid_values = [str(v) for v in unique_values if len(str(v)) <= 100]
                
                if len(valid_values) == unique_count and len(valid_values) <= enum_threshold:
                    # 为每个值分配一个数字ID
                    enum_items = [f"'{v}' = {i+1}" for i, v in enumerate(valid_values)]
                    ch_type = f"Enum8({', '.join(enum_items)})"
                    print(f"  -> 使用Enum8类型，包含{len(valid_values)}个值")
                else:
                    ch_type = 'String'
            else:
                # 检查字符串长度
                max_length = non_null_data.astype(str).str.len().max() if len(non_null_data) > 0 else 0
                if max_length > string_length_threshold:
                    ch_type = 'Text'
                    print(f"  -> 使用Text类型，最大长度: {max_length}")
                else:
                    ch_type = 'String'
                    print(f"  -> 使用String类型，最大长度: {max_length}")
        
        elif pd.api.types.is_integer_dtype(dtype):
            # 整数类型处理
            non_null_data = col_data.dropna()
            
            if len(non_null_data) == 0:
                ch_type = 'Int32'
            else:
                min_val = non_null_data.min()
                max_val = non_null_data.max()
                
                print(f"  -> 数值范围: {min_val} ~ {max_val}")
                
                # 判断是否有负数
                has_negative = min_val < 0
                
                # 根据数值范围选择合适的整数类型
                if has_negative:
                    if min_val >= -128 and max_val <= 127:
                        ch_type = 'Int8'
                    elif min_val >= -32768 and max_val <= 32767:
                        ch_type = 'Int16'
                    elif min_val >= -2147483648 and max_val <= 2147483647:
                        ch_type = 'Int32'
                    else:
                        ch_type = 'Int64'
                else:
                    if max_val <= 255:
                        ch_type = 'UInt8'
                    elif max_val <= 65535:
                        ch_type = 'UInt16'
                    elif max_val <= 4294967295:
                        ch_type = 'UInt32'
                    else:
                        ch_type = 'UInt64'
        
        elif pd.api.types.is_float_dtype(dtype):
            # 浮点数类型处理
            ch_type = 'Float64'
            
        elif pd.api.types.is_bool_dtype(dtype):
            # 布尔类型处理
            ch_type = 'Bool'
            
        elif pd.api.types.is_datetime64_any_dtype(dtype):
            # 日期时间类型处理
            ch_type = 'DateTime'
            
        else:
            # 默认类型
            ch_type = 'String'
            print(f"  -> 未识别的数据类型，使用默认String类型")
        
        # 添加Nullable包装
        if nullable and ch_type not in ['String', 'Text']:  # String类型默认可以为空
            ch_type = f'Nullable({ch_type})'
        
        print(f"  -> ClickHouse类型: {ch_type}")
        
        # 保存schema信息
        schema_info.append({
            'column_name': col_name,
            'pandas_dtype': str(dtype),
            'clickhouse_type': ch_type,
            'null_count': null_count,
            'null_ratio': null_ratio,
            'unique_count': unique_count
        })
        
    return schema_info

def override_column_types(schema_info, type_overrides):
    """
    覆盖指定列的数据类型
    
    Parameters:
    schema_info: list - 从analyze_and_generate_clickhouse_schema返回的schema信息
    type_overrides: dict - 列名到新类型的映射, 例如 {'column_name': 'NewType'}
    
    Returns:
    list - 更新后的schema信息
    """
    updated_schema = []
    
    for col_info in schema_info:
        col_name = col_info['column_name']
        
        # 创建新的列信息副本
        new_col_info = col_info.copy()
        
        # 检查是否需要覆盖类型
        if col_name in type_overrides:
            old_type = col_info['clickhouse_type']
            new_type = type_overrides[col_name]
            
            print(f"覆盖列 '{col_name}': {old_type} -> {new_type}")
            new_col_info['clickhouse_type'] = new_type
            new_col_info['type_overridden'] = True
        else:
            new_col_info['type_overridden'] = False
        
        updated_schema.append(new_col_info)
    
    return updated_schema

def print_schema_summary(schema_info):
    """
    打印schema摘要信息
    """
    print("Schema摘要:")
    print("-" * 80)
    
    total_columns = len(schema_info)
    overridden_columns = sum(1 for col in schema_info if col.get('type_overridden', False))
    
    print(f"总列数: {total_columns}")
    print(f"类型被覆盖的列数: {overridden_columns}")
    
    # 按类型分组统计
    type_count = {}
    for col in schema_info:
        col_type = col['clickhouse_type']
        # 简化类型名（去掉参数）
        simple_type = col_type.split('(')[0]
        type_count[simple_type] = type_count.get(simple_type, 0) + 1
    
    print("\n类型分布:")
    for col_type, count in sorted(type_count.items()):
        print(f"  {col_type}: {count}")
    
    # 显示被覆盖的列
    if overridden_columns > 0:
        print("\n被覆盖类型的列:")
        for col in schema_info:
            if col.get('type_overridden', False):
                print(f"  {col['column_name']}: {col['clickhouse_type']}")


def generate_create_table_from_schema(schema_info, table_name, order_by_columns=None, engine='MergeTree'):
    """
    根据schema信息生成ClickHouse建表语句
    
    Parameters:
    schema_info: list - 列schema信息
    table_name: str - 表名
    order_by_columns: list - 排序列，如果为None则使用tuple()
    engine: str - 表引擎，默认为MergeTree
    
    Returns:
    str - 完整的CREATE TABLE语句
    """
    
    # 生成列定义
    column_definitions = []
    for col_info in schema_info:
        col_name = col_info['column_name']
        col_type = col_info['clickhouse_type']
        column_definitions.append(f"    `{col_name}` {col_type}")
    
    # 生成ORDER BY子句
    if order_by_columns and len(order_by_columns) > 0:
        order_by_clause = f"ORDER BY ({', '.join(order_by_columns)})"
    else:
        order_by_clause = "ORDER BY tuple()"
    
    # 生成完整的建表语句
    tag_definitions = ',\n'.join(column_definitions)
    create_sql = f"""CREATE TABLE {table_name} (
{tag_definitions}
) ENGINE = {engine}()
{order_by_clause};"""
    
    return create_sql

In [139]:
# 使用示例
print("开始分析DataFrame schema...")
schema_info = analyze_and_generate_clickhouse_schema(cleaned_df)

print("\n" + "="*50)
print("Schema分析摘要:")
print("="*50)
schema_df = pd.DataFrame(schema_info)
display(schema_df)

开始分析DataFrame schema...

分析列: school_code
  数据类型: object
  空值数量: 0 (0.00%)
  唯一值数量: 1709
  -> 使用String类型，最大长度: 4
  -> ClickHouse类型: String

分析列: school_name
  数据类型: object
  空值数量: 0 (0.00%)
  唯一值数量: 1709
  -> 使用String类型，最大长度: 16
  -> ClickHouse类型: String

分析列: major_code
  数据类型: object
  空值数量: 0 (0.00%)
  唯一值数量: 171
  -> 使用String类型，最大长度: 2
  -> ClickHouse类型: String

分析列: major_name
  数据类型: object
  空值数量: 0 (0.00%)
  唯一值数量: 1186
  -> 使用String类型，最大长度: 15
  -> ClickHouse类型: String

分析列: major_group_code
  数据类型: object
  空值数量: 0 (0.00%)
  唯一值数量: 33
  -> 使用String类型，最大长度: 2
  -> ClickHouse类型: String

分析列: source_province
  数据类型: object
  空值数量: 0 (0.00%)
  唯一值数量: 1
  -> 使用Enum8类型，包含1个值
  -> ClickHouse类型: Enum8('湖北' = 1)

分析列: subject_category
  数据类型: object
  空值数量: 0 (0.00%)
  唯一值数量: 2
  -> 使用Enum8类型，包含2个值
  -> ClickHouse类型: Enum8('物理' = 1, '历史' = 2)

分析列: subject_requirement_raw
  数据类型: object
  空值数量: 0 (0.00%)
  唯一值数量: 11
  -> 使用Enum8类型，包含11个值
  -> ClickHouse类型: Enum8('化学' = 1, '不限' = 2, '化学+生物' = 3, '思想政治' = 4, '地理' = 5, '思想政治+地理' = 6, '生物' = 7, '化学+地理' = 8, '生物+思想政治' = 9, '生物+地理' = 10, '化学+思想政治' = 11)

分析列: tuition_fee
  数据类型: object
  空值数量: 0 (0.00%)
  唯一值数量: 522
  -> 使用String类型，最大长度: 6
  -> ClickHouse类型: String

分析列: is_new_major
  数据类型: bool
  空值数量: 0 (0.00%)
  唯一值数量: 2
  -> ClickHouse类型: Bool

分析列: admission_batch
  数据类型: object
  空值数量: 0 (0.00%)
  唯一值数量: 2
  -> 使用Enum8类型，包含2个值
  -> ClickHouse类型: Enum8('本科批' = 1, '专科批' = 2)

分析列: enrollment_plan
  数据类型: int64
  空值数量: 0 (0.00%)
  唯一值数量: 228
  -> 数值范围: 0 ~ 496
  -> ClickHouse类型: UInt16

分析列: enrollment_plan_2024
  数据类型: int64
  空值数量: 0 (0.00%)
  唯一值数量: 228
  -> 数值范围: 0 ~ 496
  -> ClickHouse类型: UInt16

分析列: study_duration
  数据类型: int64
  空值数量: 0 (0.00%)
  唯一值数量: 2
  -> 数值范围: 3 ~ 4
  -> ClickHouse类型: UInt8

分析列: major_id
  数据类型: object
  空值数量: 0 (0.00%)
  唯一值数量: 29439
  -> 使用String类型，最大长度: 8
  -> ClickHouse类型: String

分析列: enrollment_type
  数据类型: object
  空值数量: 0 (0.00%)
  唯一值数量: 6
  -> 使用Enum8类型，包含6个值
  -> ClickHouse类型: Enum8('' = 1, '国家专项计划' = 2, '地方专项计划' = 3, '专本联合培养' = 4, '单设志愿-高校专项' = 5, '单设志愿-高水平运动队' = 6)

分析列: enrollment_plan_year
  数据类型: int64
  空值数量: 0 (0.00%)
  唯一值数量: 1
  -> 数值范围: 2025 ~ 2025
  -> ClickHouse类型: UInt16

分析列: require_physics
  数据类型: bool
  空值数量: 0 (0.00%)
  唯一值数量: 2
  -> ClickHouse类型: Bool

分析列: require_chemistry
  数据类型: bool
  空值数量: 0 (0.00%)
  唯一值数量: 2
  -> ClickHouse类型: Bool

分析列: require_biology
  数据类型: bool
  空值数量: 0 (0.00%)
  唯一值数量: 2
  -> ClickHouse类型: Bool

分析列: require_politics
  数据类型: bool
  空值数量: 0 (0.00%)
  唯一值数量: 2
  -> ClickHouse类型: Bool

分析列: require_history
  数据类型: bool
  空值数量: 0 (0.00%)
  唯一值数量: 2
  -> ClickHouse类型: Bool

分析列: require_geography
  数据类型: bool
  空值数量: 0 (0.00%)
  唯一值数量: 2
  -> ClickHouse类型: Bool

分析列: major_category
  数据类型: object
  空值数量: 0 (0.00%)
  唯一值数量: 184
  -> 使用String类型，最大长度: 10
  -> ClickHouse类型: String

分析列: major_description
  数据类型: object
  空值数量: 0 (0.00%)
  唯一值数量: 7019
  -> 使用String类型，最大长度: 243
  -> ClickHouse类型: String

分析列: min_score_2024
  数据类型: int64
  空值数量: 0 (0.00%)
  唯一值数量: 469
  -> 数值范围: 0 ~ 691
  -> ClickHouse类型: UInt16

分析列: min_rank_2024
  数据类型: int64
  空值数量: 0 (0.00%)
  唯一值数量: 835
  -> 数值范围: 0 ~ 245038
  -> ClickHouse类型: UInt32

分析列: admission_num_2024
  数据类型: int64
  空值数量: 0 (0.00%)
  唯一值数量: 260
  -> 数值范围: 0 ~ 1630
  -> ClickHouse类型: UInt16

分析列: major_min_score_2024
  数据类型: int64
  空值数量: 0 (0.00%)
  唯一值数量: 481
  -> 数值范围: 0 ~ 691
  -> ClickHouse类型: UInt16

分析列: major_min_rank_2024
  数据类型: int64
  空值数量: 0 (0.00%)
  唯一值数量: 877
  -> 数值范围: 0 ~ 245038
  -> ClickHouse类型: UInt32

分析列: major_avg_score_2024
  数据类型: int64
  空值数量: 0 (0.00%)
  唯一值数量: 384
  -> 数值范围: 0 ~ 667
  -> ClickHouse类型: UInt16

分析列: major_avg_rank_2024
  数据类型: int64
  空值数量: 0 (0.00%)
  唯一值数量: 659
  -> 数值范围: 0 ~ 241696
  -> ClickHouse类型: UInt32

分析列: major_max_score_2024
  数据类型: int64
  空值数量: 0 (0.00%)
  唯一值数量: 377
  -> 数值范围: 0 ~ 671
  -> ClickHouse类型: UInt16

分析列: major_max_rank_2024
  数据类型: int64
  空值数量: 0 (0.00%)
  唯一值数量: 670
  -> 数值范围: 0 ~ 241100
  -> ClickHouse类型: UInt32

分析列: major_admission_num_2024
  数据类型: int64
  空值数量: 0 (0.00%)
  唯一值数量: 169
  -> 数值范围: 0 ~ 374
  -> ClickHouse类型: UInt16

分析列: school_province
  数据类型: object
  空值数量: 0 (0.00%)
  唯一值数量: 31
  -> 使用String类型，最大长度: 3
  -> ClickHouse类型: String

分析列: school_city
  数据类型: object
  空值数量: 0 (0.00%)
  唯一值数量: 345
  -> 使用String类型，最大长度: 5
  -> ClickHouse类型: String

分析列: school_type
  数据类型: object
  空值数量: 0 (0.00%)
  唯一值数量: 36
  -> 使用String类型，最大长度: 8
  -> ClickHouse类型: String

分析列: school_ownership
  数据类型: object
  空值数量: 0 (0.00%)
  唯一值数量: 5
  -> 使用Enum8类型，包含5个值
  -> ClickHouse类型: Enum8('公办' = 1, '内地与港澳台合作办学' = 2, '中外合作办学' = 3, '民办' = 4, '境外高校独立办学' = 5)

分析列: education_level
  数据类型: object
  空值数量: 0 (0.00%)
  唯一值数量: 3
  -> 使用Enum8类型，包含3个值
  -> ClickHouse类型: Enum8('本科' = 1, '职业本科' = 2, '专科' = 3)

分析列: school_authority
  数据类型: object
  空值数量: 0 (0.00%)
  唯一值数量: 30
  -> 使用String类型，最大长度: 14
  -> ClickHouse类型: String

分析列: school_level
  数据类型: object
  空值数量: 0 (0.00%)
  唯一值数量: 4
  -> 使用Enum8类型，包含4个值
  -> ClickHouse类型: Enum8('985,211,双一流' = 1, '双一流' = 2, '211,双一流' = 3, '' = 4)

分析列: school_tags
  数据类型: object
  空值数量: 0 (0.00%)
  唯一值数量: 380
  -> 使用String类型，最大长度: 92
  -> ClickHouse类型: String

分析列: id
  数据类型: int64
  空值数量: 0 (0.00%)
  唯一值数量: 29439
  -> 数值范围: 1 ~ 29439
  -> ClickHouse类型: UInt16

分析列: is_science
  数据类型: bool
  空值数量: 0 (0.00%)
  唯一值数量: 2
  -> ClickHouse类型: Bool

分析列: is_engineering
  数据类型: bool
  空值数量: 0 (0.00%)
  唯一值数量: 2
  -> ClickHouse类型: Bool

分析列: is_medical
  数据类型: bool
  空值数量: 0 (0.00%)
  唯一值数量: 2
  -> ClickHouse类型: Bool

分析列: is_economics_mgmt_law
  数据类型: bool
  空值数量: 0 (0.00%)
  唯一值数量: 2
  -> ClickHouse类型: Bool

分析列: is_liberal_arts
  数据类型: bool
  空值数量: 0 (0.00%)
  唯一值数量: 2
  -> ClickHouse类型: Bool

分析列: is_design_arts
  数据类型: bool
  空值数量: 0 (0.00%)
  唯一值数量: 2
  -> ClickHouse类型: Bool

分析列: is_language
  数据类型: bool
  空值数量: 0 (0.00%)
  唯一值数量: 2
  -> ClickHouse类型: Bool

==================================================
Schema分析摘要:
==================================================

,column_name,pandas_dtype,clickhouse_type,null_count,null_ratio,unique_count
0,school_code,object,String,0,0.0,1709
1,school_name,object,String,0,0.0,1709
2,major_code,object,String,0,0.0,171
3,major_name,object,String,0,0.0,1186
4,major_group_code,object,String,0,0.0,33
5,source_province,object,Enum8('湖北' = 1),0,0.0,1
6,subject_category,object,"Enum8('物理' = 1, '历史' = 2)",0,0.0,2
7,subject_requirement_raw,object,"Enum8('化学' = 1, '不限' = 2, '化学+生物' = 3, '思想政治' ...",0,0.0,11
8,tuition_fee,object,String,0,0.0,522
9,is_new_major,bool,Bool,0,0.0,2
10,admission_batch,object,"Enum8('本科批' = 1, '专科批' = 2)",0,0.0,2
11,enrollment_plan,int64,UInt16,0,0.0,228
12,enrollment_plan_2024,int64,UInt16,0,0.0,228
13,study_duration,int64,UInt8,0,0.0,2
14,major_id,object,String,0,0.0,29439
15,enrollment_type,object,"Enum8('' = 1, '国家专项计划' = 2, '地方专项计划' = 3, '专本联...",0,0.0,6
16,enrollment_plan_year,int64,UInt16,0,0.0,1
17,require_physics,bool,Bool,0,0.0,2
18,require_chemistry,bool,Bool,0,0.0,2
19,require_biology,bool,Bool,0,0.0,2
20,require_politics,bool,Bool,0,0.0,2
21,require_history,bool,Bool,0,0.0,2
22,require_geography,bool,Bool,0,0.0,2
23,major_category,object,String,0,0.0,184
24,major_description,object,String,0,0.0,7019
25,min_score_2024,int64,UInt16,0,0.0,469
26,min_rank_2024,int64,UInt32,0,0.0,835
27,admission_num_2024,int64,UInt16,0,0.0,260
28,major_min_score_2024,int64,UInt16,0,0.0,481
29,major_min_rank_2024,int64,UInt32,0,0.0,877
30,major_avg_score_2024,int64,UInt16,0,0.0,384
31,major_avg_rank_2024,int64,UInt32,0,0.0,659
32,major_max_score_2024,int64,UInt16,0,0.0,377
33,major_max_rank_2024,int64,UInt32,0,0.0,670
34,major_admission_num_2024,int64,UInt16,0,0.0,169
35,school_province,object,String,0,0.0,31
36,school_city,object,String,0,0.0,345
37,school_type,object,String,0,0.0,36
38,school_ownership,object,"Enum8('公办' = 1, '内地与港澳台合作办学' = 2, '中外合作办学' = 3...",0,0.0,5
39,education_level,object,"Enum8('本科' = 1, '职业本科' = 2, '专科' = 3)",0,0.0,3
40,school_authority,object,String,0,0.0,30
41,school_level,object,"Enum8('985,211,双一流' = 1, '双一流' = 2, '211,双一流' ...",0,0.0,4
42,school_tags,object,String,0,0.0,380
43,id,int64,UInt16,0,0.0,29439
44,is_science,bool,Bool,0,0.0,2
45,is_engineering,bool,Bool,0,0.0,2
46,is_medical,bool,Bool,0,0.0,2
47,is_economics_mgmt_law,bool,Bool,0,0.0,2
48,is_liberal_arts,bool,Bool,0,0.0,2
49,is_design_arts,bool,Bool,0,0.0,2
50,is_language,bool,Bool,0,0.0,2

In [140]:
# 修改列属性
override_schema_info = override_column_types(schema_info=schema_info, type_overrides={
    'subject_requirement_raw': 'String',
    'school_level': 'String',
    'id': 'UInt32',
})
print_schema_summary(override_schema_info)

覆盖列 'subject_requirement_raw': Enum8('化学' = 1, '不限' = 2, '化学+生物' = 3, '思想政治' = 4, '地理' = 5, '思想政治+地理' = 6, '生物' = 7, '化学+地理' = 8, '生物+思想政治' = 9, '生物+地理' = 10, '化学+思想政治' = 11) -> String
覆盖列 'school_level': Enum8('985,211,双一流' = 1, '双一流' = 2, '211,双一流' = 3, '' = 4) -> String
覆盖列 'id': UInt16 -> UInt32
Schema摘要:
--------------------------------------------------------------------------------
总列数: 51
类型被覆盖的列数: 3

类型分布:
  Bool: 14
  Enum8: 6
  String: 16
  UInt16: 9
  UInt32: 5
  UInt8: 1

被覆盖类型的列:
  subject_requirement_raw: String
  school_level: String
  id: UInt32

In [145]:
# 预览表结构
order_by_columns = ['id']
table_name = 'gaokao2025'

print(generate_create_table_from_schema(override_schema_info, order_by_columns=order_by_columns, table_name=table_name))

CREATE TABLE gaokao2025 (
    `school_code` String,
    `school_name` String,
    `major_code` String,
    `major_name` String,
    `major_group_code` String,
    `source_province` Enum8('湖北' = 1),
    `subject_category` Enum8('物理' = 1, '历史' = 2),
    `subject_requirement_raw` String,
    `tuition_fee` String,
    `is_new_major` Bool,
    `admission_batch` Enum8('本科批' = 1, '专科批' = 2),
    `enrollment_plan` UInt16,
    `enrollment_plan_2024` UInt16,
    `study_duration` UInt8,
    `major_id` String,
    `enrollment_type` Enum8('' = 1, '国家专项计划' = 2, '地方专项计划' = 3, '专本联合培养' = 4, '单设志愿-高校专项' = 5, '单设志愿-高水平运动队' = 6),
    `enrollment_plan_year` UInt16,
    `require_physics` Bool,
    `require_chemistry` Bool,
    `require_biology` Bool,
    `require_politics` Bool,
    `require_history` Bool,
    `require_geography` Bool,
    `major_category` String,
    `major_description` String,
    `min_score_2024` UInt16,
    `min_rank_2024` UInt32,
    `admission_num_2024` UInt16,
    `major_min_score_2024` UInt16,
    `major_min_rank_2024` UInt32,
    `major_avg_score_2024` UInt16,
    `major_avg_rank_2024` UInt32,
    `major_max_score_2024` UInt16,
    `major_max_rank_2024` UInt32,
    `major_admission_num_2024` UInt16,
    `school_province` String,
    `school_city` String,
    `school_type` String,
    `school_ownership` Enum8('公办' = 1, '内地与港澳台合作办学' = 2, '中外合作办学' = 3, '民办' = 4, '境外高校独立办学' = 5),
    `education_level` Enum8('本科' = 1, '职业本科' = 2, '专科' = 3),
    `school_authority` String,
    `school_level` String,
    `school_tags` String,
    `id` UInt32,
    `is_science` Bool,
    `is_engineering` Bool,
    `is_medical` Bool,
    `is_economics_mgmt_law` Bool,
    `is_liberal_arts` Bool,
    `is_design_arts` Bool,
    `is_language` Bool
) ENGINE = MergeTree()
ORDER BY (id);

#### 执行计划

---

In [146]:
def create_table_from_schema(client, schema_info, table_name, order_by_columns=None):
    """
    仅创建ClickHouse表
    
    Parameters:
    client: ClickHouse客户端
    schema_info: list - schema信息
    table_name: str - 表名
    order_by_columns: list - 排序列
    
    Returns:
    bool - 是否成功
    """
    try:
        # 1. 删除旧表（如果存在）
        # 警告：此操作会删除现有表及其数据，请谨慎使用！
        print(f"正在删除旧表 {table_name}（如果存在）, 确认继续？")
        confirm = input("输入 'y' 继续，其他键取消: ")
        if confirm.lower() != 'y':
            print("操作已取消")
            return False

        drop_sql = f"DROP TABLE IF EXISTS {table_name}"
        client.command(drop_sql)
        print(f"✓ 删除旧表 {table_name}（如果存在）")
        
        # 2. 生成并执行建表语句
        create_sql = generate_create_table_from_schema(schema_info, table_name, order_by_columns)
        print("建表语句:")
        print("-" * 60)
        print(create_sql)
        print("-" * 60)
        
        client.command(create_sql)
        print(f"✓ 创建表 {table_name} 成功")
        
        return True
        
    except Exception as e:
        print(f"❌ 创建表失败: {e}")
        return False

def insert_data_to_table(client, df, table_name):
    """
    仅向已存在的表插入数据
    
    Parameters:
    client: ClickHouse客户端
    df: pandas.DataFrame - 要插入的数据
    table_name: str - 表名
    
    Returns:
    bool - 是否成功
    """
    try:
        print(f"准备插入 {len(df)} 行数据到表 {table_name}...")
        
        # 直接插入数据，不做任何预处理
        client.insert_df(table_name, df)
        print(f"✓ 数据插入成功")
        
        # 验证插入结果
        result = client.query(f"SELECT COUNT(*) as count FROM {table_name}")
        row_count = result.result_rows[0][0]
        print(f"✓ 表中共有 {row_count} 行数据")
        
        return True
        
    except Exception as e:
        print(f"❌ 数据插入失败: {e}")
        import traceback
        traceback.print_exc()
        return False

In [147]:
# 使用示例：
print("=" * 60)
print("1. 创建表")
print("=" * 60)

# 先创建表
create_success = create_table_from_schema(
    client=client,
    schema_info=override_schema_info,
    table_name=table_name,
    order_by_columns=order_by_columns
)

============================================================
1. 创建表
============================================================
正在删除旧表 gaokao2025（如果存在）, 确认继续？
✓ 删除旧表 gaokao2025（如果存在）
建表语句:
------------------------------------------------------------
CREATE TABLE gaokao2025 (
    `school_code` String,
    `school_name` String,
    `major_code` String,
    `major_name` String,
    `major_group_code` String,
    `source_province` Enum8('湖北' = 1),
    `subject_category` Enum8('物理' = 1, '历史' = 2),
    `subject_requirement_raw` String,
    `tuition_fee` String,
    `is_new_major` Bool,
    `admission_batch` Enum8('本科批' = 1, '专科批' = 2),
    `enrollment_plan` UInt16,
    `enrollment_plan_2024` UInt16,
    `study_duration` UInt8,
    `major_id` String,
    `enrollment_type` Enum8('' = 1, '国家专项计划' = 2, '地方专项计划' = 3, '专本联合培养' = 4, '单设志愿-高校专项' = 5, '单设志愿-高水平运动队' = 6),
    `enrollment_plan_year` UInt16,
    `require_physics` Bool,
    `require_chemistry` Bool,
    `require_biology` Bool,
    `require_politics` Bool,
    `require_history` Bool,
    `require_geography` Bool,
    `major_category` String,
    `major_description` String,
    `min_score_2024` UInt16,
    `min_rank_2024` UInt32,
    `admission_num_2024` UInt16,
    `major_min_score_2024` UInt16,
    `major_min_rank_2024` UInt32,
    `major_avg_score_2024` UInt16,
    `major_avg_rank_2024` UInt32,
    `major_max_score_2024` UInt16,
    `major_max_rank_2024` UInt32,
    `major_admission_num_2024` UInt16,
    `school_province` String,
    `school_city` String,
    `school_type` String,
    `school_ownership` Enum8('公办' = 1, '内地与港澳台合作办学' = 2, '中外合作办学' = 3, '民办' = 4, '境外高校独立办学' = 5),
    `education_level` Enum8('本科' = 1, '职业本科' = 2, '专科' = 3),
    `school_authority` String,
    `school_level` String,
    `school_tags` String,
    `id` UInt32,
    `is_science` Bool,
    `is_engineering` Bool,
    `is_medical` Bool,
    `is_economics_mgmt_law` Bool,
    `is_liberal_arts` Bool,
    `is_design_arts` Bool,
    `is_language` Bool
) ENGINE = MergeTree()
ORDER BY (id);
------------------------------------------------------------
✓ 创建表 gaokao2025 成功

In [148]:
if create_success:
    print("\n" + "=" * 60)
    print("2. 插入数据")
    print("=" * 60)
    
    # 再插入数据
    insert_success = insert_data_to_table(
        client=client,
        df=cleaned_df,
        table_name="gaokao2025"
    )
    
    if insert_success:
        print("\n🎉 表创建和数据插入都完成了！")
    else:
        print("\n❌ 数据插入失败")
else:
    print("\n❌ 表创建失败")

============================================================
2. 插入数据
============================================================
准备插入 29439 行数据到表 gaokao2025...
✓ 数据插入成功
✓ 表中共有 29439 行数据

🎉 表创建和数据插入都完成了！